classDiagram

class Veterinaria {

}
class Sucursal {

}
class Empleado {

}
class TipoEmpleado {

}
class Raza {
    
}
class Perro {

}
class Vacunas {

}
class Sintoma {

}
class Diagnostico {

}
class Medicamento {

}
