# Generated by Django 4.2.6 on 2023-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usuario_numerodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaIngreso',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
