# Generated by Django 4.2.4 on 2023-10-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_asignacionempleados_consulta_empleado_estadoempleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='id',
        ),
        migrations.AlterField(
            model_name='perro',
            name='numeroHistoriaClinica',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
