# Generated by Django 4.2.4 on 2023-11-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_asignacionempleados_consulta_empleado_estadoempleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudia', models.BooleanField(default=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='AsignacionEmpleados',
            new_name='HistorialEmpleado',
        ),
        migrations.DeleteModel(
            name='RolEmpleado',
        ),
        migrations.RenameField(
            model_name='estadoempleado',
            old_name='estudiante',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='historialempleado',
            old_name='fechaEgreso',
            new_name='fechaFin',
        ),
        migrations.RenameField(
            model_name='historialempleado',
            old_name='fechaIngreso',
            new_name='fechaInicio',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='numeroOrden',
        ),
        migrations.RemoveField(
            model_name='estadoempleado',
            name='noTrabaja',
        ),
        migrations.RemoveField(
            model_name='estadoempleado',
            name='recibido',
        ),
        migrations.RemoveField(
            model_name='estadoempleado',
            name='trabaja',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='numeroHistoriaClinica',
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.estadoempleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estadoempleado',
            name='estado',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
