# Generated by Django 4.2.4 on 2023-10-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_perro_id_alter_perro_numerohistoriaclinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perro',
            name='numeroHistoriaClinica',
            field=models.IntegerField(),
        ),
    ]
