classDiagram
class Veterinaria {
  -String nombre
  -sucursales sucursal

  +new()
  +agregarSucursal()
}
class Sucursal {
  -int id
  -String direccion
  -empleados empleado
  -perros perro
  -consultas consulta

  +new()
  +agregarEmpleado()
  +agregarPerro()
  +agregarConsulta()
}
class Empleado {
  -String numeroDocumento
  -String nombres
  -String apellido
  -date fechaNacimiento
  -date fechaIngreso
  -sucursal sucursal

  +new()
  +verificarRecibido()
  +generarNumHistoriaClinicaPerro()
  
}
class Perro {
  -int numeroHistoriaClinica
  -String nombre
  -date fechaNacimiento
  -raza raza
  -float pesoActual
  -float alturaActual
  -duenio duenio
  -String consulta
  -String vacuna

  +new()
}
class Raza {
  -String denominacion
  -float pesoMinimoMachos
  -float pesoMaximoMachos
  -float pesoMinimoHembras
  -float pesoMaximoHembras
  -float alturaMediaMachos
  -float alturaMediaHembras
  -float cuidadosEspeciales

  +new()
}
class Consulta {
  -int numero_orden
  -int numeroHistoriaClinica_perro
  -date fechaEntrada
  -String num_doc_empleado
  -String sintomas
  -String diagnosticos
  -String medicamento
  -date fechaSalida

  +new()
  +recetarMedicamentos()
}
class Vacuna {
  -String tipo
  -date fechaProgramada
  -date fechaReal
  -String empleado
  -String laboratorio
  -String dosis

  +new()
}
class Medicamento {
  -String nombre
  -String laboratorio
  -date fechaUltimaCompra
  -int cantidadExistente
  -int cantidadMinima

  +new()
}

class DuenioPerro {
  -String apellido
  -String nombres
  -String telefono

  +new()
}
class EstadoEmpleado {
  -String estudiante
  -String recibido
}
class Rol {
  -String supervisor
  -String supervisor_suplente
}

Veterinaria --> Sucursal
Sucursal "1" <-- "*" Empleado
Sucursal "1" <-- "*" Consulta
Sucursal "*" <-- "*" Perro
Empleado --> EstadoEmpleado
Perro "*" --> "1" Raza
Perro "1" <-- "*" Consulta
Perro "1" <-- "*" Vacuna
Consulta "1" --> "*" Medicamento
DuenioPerro "*" <-- "*" Perro
EstadoEmpleado "1" --> Rol
